/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Themes */
        get: operations["themes_api_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_api_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Similar Reviews
         * @description Nearest neighbours by summary embedding (pgvector cosine distance).
         */
        get: operations["similar_reviews_api_reviews__review_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Releases */
        get: operations["list_releases_api_releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description Compare a release with the one before it (or with `baseline`).
         */
        get: operations["compare_api_releases_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/regressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regressions
         * @description Every flagged segment across consecutive release pairs.
         */
        get: operations["regressions_api_releases_regressions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Replies */
        get: operations["list_replies_api_replies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies/{reply_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reply */
        get: operations["get_reply_api_replies__reply_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies/{reply_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_replies__reply_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies/{reply_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit */
        post: operations["edit_api_replies__reply_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies/{reply_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_replies__reply_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies/{reply_id}/redraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redraft */
        post: operations["redraft_api_replies__reply_id__redraft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replies/{reply_id}/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post
         * @description Post an approved reply. Without store keys and POSTING_ENABLED this is a dry run.
         */
        post: operations["post_api_replies__reply_id__post_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorBody */
        ActorBody: {
            /** Actor */
            actor: string;
        };
        /** AuditView */
        AuditView: {
            action: components["schemas"]["ReplyAction"];
            from_state: components["schemas"]["ReplyState"] | null;
            to_state: components["schemas"]["ReplyState"];
            /** Actor */
            actor: string;
            /** Note */
            note: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "crash" | "performance" | "login" | "payments" | "ux" | "feature_request" | "praise" | "other";
        /** CategoryCount */
        CategoryCount: {
            category: components["schemas"]["Category"];
            /** Count */
            count: number;
        };
        /** EditBody */
        EditBody: {
            /** Actor */
            actor: string;
            /** Body */
            body: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: boolean;
            /** Model */
            model: string;
            /** Demo Mode */
            demo_mode: boolean;
        };
        /** OverviewView */
        OverviewView: {
            /** Total Reviews */
            total_reviews: number;
            /** Avg Rating */
            avg_rating: number | null;
            /** Negative Share */
            negative_share: number | null;
            /** Pending Replies */
            pending_replies: number;
            /** Weekly */
            weekly: components["schemas"]["WeekPoint"][];
            /** Categories */
            categories: components["schemas"]["CategoryCount"][];
            /** Stores */
            stores: {
                [key: string]: number;
            };
            usage: components["schemas"]["UsageTotals"];
            /** Model */
            model: string;
            /** Demo Mode */
            demo_mode: boolean;
        };
        /** Page[ReplyView] */
        Page_ReplyView_: {
            /** Items */
            items: components["schemas"]["ReplyView"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ReviewView] */
        Page_ReviewView_: {
            /** Items */
            items: components["schemas"]["ReviewView"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** RejectBody */
        RejectBody: {
            /** Actor */
            actor: string;
            /** Note */
            note?: string | null;
        };
        /** ReleaseComparisonView */
        ReleaseComparisonView: {
            baseline: components["schemas"]["ReleaseSummaryView"];
            candidate: components["schemas"]["ReleaseSummaryView"];
            /** Alpha */
            alpha: number;
            /** Min Ratio */
            min_ratio: number;
            /** Min Count */
            min_count: number;
            /** Segments */
            segments: components["schemas"]["SegmentComparisonView"][];
        };
        /** ReleaseSummaryView */
        ReleaseSummaryView: {
            /** Version */
            version: string;
            /** Reviews */
            reviews: number;
            /** Avg Rating */
            avg_rating: number | null;
            /** Negative Share */
            negative_share: number | null;
            /**
             * First Review At
             * Format: date-time
             */
            first_review_at: string;
        };
        /**
         * ReplyAction
         * @enum {string}
         */
        ReplyAction: "draft" | "approve" | "edit" | "reject" | "redraft" | "post" | "dry_run_post";
        /**
         * ReplyState
         * @enum {string}
         */
        ReplyState: "draft" | "approved" | "edited" | "rejected" | "posted" | "would_post";
        /** ReplyView */
        ReplyView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            state: components["schemas"]["ReplyState"];
            /** Body */
            body: string;
            /** Drafted Body */
            drafted_body: string;
            /** Char Limit */
            char_limit: number;
            /** Model Name */
            model_name: string;
            /** Approved By */
            approved_by: string | null;
            /** Approved At */
            approved_at: string | null;
            /** Posted At */
            posted_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Allowed Actions */
            allowed_actions: components["schemas"]["ReplyAction"][];
            review: components["schemas"]["ReviewView"];
            /** Audit */
            audit: components["schemas"]["AuditView"][];
        };
        /** ReviewView */
        ReviewView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            store: components["schemas"]["Store"];
            /** External Id */
            external_id: string;
            /** Rating */
            rating: number;
            /** Title */
            title: string | null;
            /** Body */
            body: string;
            /** Language */
            language: string | null;
            /** App Version */
            app_version: string | null;
            /** Territory */
            territory: string | null;
            /** Author */
            author: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            triage: components["schemas"]["TriageView"] | null;
            /** Theme Id */
            theme_id?: string | null;
            /** Theme Title */
            theme_title?: string | null;
            reply_state?: components["schemas"]["ReplyState"] | null;
        };
        /** SegmentComparisonView */
        SegmentComparisonView: {
            /** Baseline Version */
            baseline_version: string;
            /** Candidate Version */
            candidate_version: string;
            kind: components["schemas"]["SegmentKind"];
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Baseline Count */
            baseline_count: number;
            /** Candidate Count */
            candidate_count: number;
            /** Baseline Rate */
            baseline_rate: number;
            /** Candidate Rate */
            candidate_rate: number;
            /** Rate Ratio */
            rate_ratio: number | null;
            /** Z */
            z: number;
            /** P Value */
            p_value: number;
            /** Adjusted P Value */
            adjusted_p_value: number;
            /** Flagged */
            flagged: boolean;
            /** Headline */
            headline: string;
        };
        /**
         * SegmentKind
         * @enum {string}
         */
        SegmentKind: "category" | "theme";
        /**
         * Sentiment
         * @enum {string}
         */
        Sentiment: "positive" | "neutral" | "negative";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /**
         * Store
         * @enum {string}
         */
        Store: "app_store" | "google_play";
        /** ThemeView */
        ThemeView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Size */
            size: number;
            dominant_category: components["schemas"]["Category"];
            trend: components["schemas"]["Trend"];
            /** Weekly Counts */
            weekly_counts: number[];
            /** Negative Share */
            negative_share: number;
            /** Representatives */
            representatives: components["schemas"]["ReviewView"][];
        };
        /**
         * Trend
         * @enum {string}
         */
        Trend: "rising" | "falling" | "stable";
        /** TriageView */
        TriageView: {
            sentiment: components["schemas"]["Sentiment"];
            category: components["schemas"]["Category"];
            severity: components["schemas"]["Severity"];
            /** Summary */
            summary: string;
            /** Language */
            language: string;
            /** Model Name */
            model_name: string;
        };
        /** UsageTotals */
        UsageTotals: {
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeekPoint */
        WeekPoint: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Reviews */
            reviews: number;
            /** Avg Rating */
            avg_rating: number | null;
            /** Negative Share */
            negative_share: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    themes_api_themes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeView"][];
                };
            };
        };
    };
    list_reviews_api_reviews_get: {
        parameters: {
            query?: {
                store?: components["schemas"]["Store"] | null;
                category?: components["schemas"]["Category"] | null;
                sentiment?: components["schemas"]["Sentiment"] | null;
                severity?: components["schemas"]["Severity"] | null;
                version?: string | null;
                rating?: number | null;
                theme_id?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReviewView_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_review_api_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    similar_reviews_api_reviews__review_id__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_releases_api_releases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseSummaryView"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_api_releases_compare_get: {
        parameters: {
            query?: {
                candidate?: string | null;
                baseline?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseComparisonView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regressions_api_releases_regressions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentComparisonView"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_replies_api_replies_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["ReplyState"] | null;
                store?: components["schemas"]["Store"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReplyView_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_reply_api_replies__reply_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reply_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approve_api_replies__reply_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reply_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    edit_api_replies__reply_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reply_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_api_replies__reply_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reply_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    redraft_api_replies__reply_id__redraft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reply_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_api_replies__reply_id__post_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reply_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid state transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
